Newyorktimes
Igors78/NewYorkTimes_clone pull request #6
Opened 2020-09-30 12:09 UTC by Igors78

Create the new pull request to test linters

2020-09-30 13:01 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**


- [ ]  Please resolve conflicts from this branch. 

- [ ] Please add more description in PR, otherwise, this project will inavlidate next time. 

- [ ] Please make the logo a link
![chrome-capture (22)](https://user-images.githubusercontent.com/58504655/94687909-4f6bf000-0346-11eb-80de-e93c58a9125d.jpg)

- [ ]  **Optional** Please add 1 - 2 lines of description about this project in the repo about section. 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-09-30 14:17 UTC, Igors78 commented
This project is the third in the Microverse HTML/CSS curriculum. We made a clone of the New York Times article page, made it look as possible closer to the original while practicing CSS3 positioning techniques like flex and grid. The header positioned fixed to the top of the page. The main section laid out using the flexbox technique, except the middle part of the page, where the grid layout covers the background image. Footer styled by flexing the containers. Aside element of the main container positioned as a flex element. Linters tests passed, no conflicts for merging.

2020-09-30 15:02 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! 
## I admire the effort put on the project, It looks almost identical! :clap: :clap:

## Required Changes
### [Mandatory] :red_circle: 

- [ ] Edit Pull Request message and copy-paste the message in the comment.
![image](https://user-images.githubusercontent.com/25774518/94701306-232e8000-0302-11eb-93d0-179cb8244185.png)

- [x] NYT logo in footer should be a link also

- [ ] Footer elements should be links
![image](https://user-images.githubusercontent.com/25774518/94702085-fd55ab00-0302-11eb-9642-df79f3a3f4cd.png)

- [ ] Leave out the ```cursor: pointer``` and convert link elements to links. We should inspect the website using the browser's inspector mode to see which elements are links instead of mimicking the mouse pointer effect.


### [OPTIONAL]  :large_blue_circle: 

- [ ] Prefer semantic HTML tags over general ```div``` container in aside editors pick section. See inline comments.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-30 15:13 UTC, jubaan requested changes

2020-09-30 15:13 UTC, jubaan commented on index.html
> +        </aside>
This could be improved:
```
<aside class="editors-pick">
  <h5 class="editors-pick__title">Editors’ Picks</h5>
  <ul class="editors-pick__body">
    <li class="editors-pick__item>
      <img class="item__img" ....>
      <h3 class="item__title"><a href=#> ... </a></h3>
    </li>
    <li class="editors-pick__item>
      <img class="item__img" ....>
      <h3 class="item__title"><a href=#> ... </a></h3>
    </li>
    <li class="editors-pick__item>
      <img class="item__img" ....>
      <h3 class="item__title"><a href=#> ... </a></h3>
    </li>
  </ul>
<aside>
```

2020-09-30 18:53 UTC, Igors78 commented
This project is the third in the Microverse HTML/CSS curriculum. We made a clone of the New York Times article page, made it look as possible closer to the original while practicing CSS3 positioning techniques like flex and grid. The header positioned fixed to the top of the page. The main section laid out using the flexbox technique, except the middle part of the page, where the grid layout covers the background image. Footer styled by flexing the containers. Aside element of the main container positioned as a flex element. Linters tests passed, no conflicts for merging. Footer content restructured to links, both logos converted to links, aside element changed to use semantic tags and remove the unnecessary wrapping divs

2020-09-30 18:54 UTC, Igors78 commented
This project is the third in the Microverse HTML/CSS curriculum. We made a clone of the New York Times article page, made it look as possible closer to the original while practicing CSS3 positioning techniques like flex and grid. The header positioned fixed to the top of the page. The main section laid out using the flexbox technique, except the middle part of the page, where the grid layout covers the background image. Footer styled by flexing the containers. Aside element of the main container positioned as a flex element. Linters tests passed, no conflicts for merging. Footer content restructured to links, both logos converted to links, aside element changed to use semantic tags and remove the unnecessary wrapping divs

2020-09-30 19:28 UTC, blackpintz requested changes
# Status: Changes Required.

## Hello team,

**Great job on your project. The one requirement that is missing on your project is the bottom sticky footer. Please check the original page and add it.**

**Also, on the Getting Started section in the readme file, add instructions on how one can set up your project locally and the necessary tools required.**

# Optional

- **Author section in the readme file, use your username handle instead of @github and @twitter.**

### Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-10-01 05:14 UTC, Igors78 commented
Readme up to date. Can not find the sticky footer anywhere in the source page, the project made according to TOP source https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0

2020-10-01 05:39 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

- [x] **Note** I am approving this project because on your system you cannot see sticky footer. If you find it somewhere else, please work on it later. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-01 08:17 UTC, merged